name: Run main.py and upload result

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # 可手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run check
        run: |
          uv run ruff format . --diff
          uv run mypy .
          uv run ruff check .

      - name: Build
        run: uv run python3 main.py

      - name: Upload gdbserver
        uses: actions/upload-artifact@v4
        with:
          name: static-gdbserver
          path: build-dir/result